[de MODULE_INFO
  ("name"       "awscurl")
  ("version"    "0.7.0")
  ("summary"    "PicoLisp AWS CLI tool using OpenSSL and Curl")
  ("source"     "https://github.com/aw/picolisp-awscurl.git")
  ("author"     "Alexander Williams")
  ("license"    "MIT")
  ("copyright"  "(c) 2018 Alexander Williams, Unscramble <license@unscramble.jp>")
  ("install"    "make")
  ("requires"
    ("picolisp-unit"    "v3.0.0"        "https://github.com/aw/picolisp-unit.git") ]
